// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    return $.fn.alignMe = function(options) {
      var defaults, nX, nY, posX, posY;
      defaults = {
        horizontal: "center",
        vertical: "center",
        offsetX: 0,
        offsetY: 0
      };
      options = $.extend(defaults, options);
      switch (options['horizontal']) {
        case "left":
        case "center":
          posX = "left";
          break;
        case "right":
          posX = "right";
          break;
        default:
          posX = "left";
      }
      switch (options['vertical']) {
        case "top":
        case "center":
        case "middle":
          posY = "top";
          break;
        case "bottom":
          posY = "bottom";
          break;
        default:
          posY = "top";
      }
      if (options['horizontal'] === "left" || options['horizontal'] === "right") {
        nX = 0;
      } else {
        nX = -((this.outerWidth() / 2) - options['offsetX']);
      }
      if (options['vertical'] === "top" || options['vertical'] === "bottom") {
        nY = 0;
      } else {
        nY = -((this.outerHeight() / 2) - options['offsetY']);
      }
      this.parent().css("position", "relative");
      this.css("position", "absolute");
      console.log("posX = " + posX + ", posY = " + posY + ", nX = " + nX + ", nY = " + nY);
      if (options['horizontal'] === "center" && options['vertical'] !== "center") {
        this.css({
          "left": "50%",
          posY: 0 + options['offsetY'] + "px",
          "margin-left": nX + "px"
        });
      } else if (options['horizontal'] !== "center" && options['vertical'] === "center") {
        this.css({
          "top": "50%",
          "margin-top": nY + "px"
        });
      } else if (options['horizontal'] === "center" && options['vertical'] === "center") {
        this.css({
          "top": "50%",
          "left": "50%",
          "margin-top": nY + "px",
          "margin-left": nX + "px"
        });
      }
      if (options['horizontal'] === "left") {
        this.css({
          "left": 0 + options['offsetX'] + "px"
        });
      } else if (options['horizontal'] === "right") {
        this.css({
          "right": 0 + options['offsetX'] + "px"
        });
      }
      if (options['vertical'] === "top") {
        return this.css({
          "top": 0 + options['offsetX'] + "px"
        });
      } else if (options['vertical'] === "bottom") {
        return this.css({
          "bottom": 0 + options['offsetX'] + "px"
        });
      }
    };
  })(jQuery);

}).call(this);
